#!/bin/bash
# Deployment-Skript für Plesk-Server
# Dieses Skript muss auf dem Produktionsserver ausgeführt werden!

echo "=== Deployment-Skript für Lizenzverwaltung ==="
echo ""
echo "WICHTIG: Dieses Skript muss auf dem Plesk-Server ausgeführt werden!"
echo ""
echo "Schritte für manuelles Deployment:"
echo ""
echo "1. Per SSH auf den Server verbinden:"
echo "   ssh DEIN_BENUTZER@5-9-96-43.plesk.page"
echo ""
echo "2. Ins Projektverzeichnis wechseln:"
echo "   cd /var/www/vhosts/DEINE_DOMAIN/httpdocs"
echo "   ODER"
echo "   cd ~/httpdocs"
echo ""
echo "3. Git-Änderungen pullen:"
echo "   git pull origin main"
echo ""
echo "4. Falls Git noch nicht initialisiert ist:"
echo "   git clone https://github.com/ManuWo94/verwaltungssystem-scarlethorizon.git ."
echo ""
echo "=== Alternative: FTP/Plesk File Manager ==="
echo ""
echo "Wenn kein SSH-Zugang verfügbar ist:"
echo "1. Plesk Panel öffnen"
echo "2. File Manager öffnen"
echo "3. Folgende Datei hochladen:"
echo "   - modules/licenses.php"
echo "   - modules/license_categories.php"
echo ""
echo "=== Dateien, die aktualisiert werden müssen ==="
echo "- modules/licenses.php (TG-Nummer, db.php Include, Syntax-Fixes)"
echo "- modules/license_categories.php (Modal-Fix)"
echo ""
